---
EnableDefaultLinters: true
exclude:
  - "app/views/layouts/_notice.html.erb"
  - "node_modules/**/*"
  - "vendor/**/*"
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Style/StringLiterals:
        Enabled: false
